### ISSUE TITLE
NPE when running Hazelcast example in Kubernetes

### ISSUE THREAD

**Issue by mwielgus** [pires/hazelcast-kubernetes-bootstrapper#8]
```
2015-10-01 15:09:28.855  INFO 7 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.runCommandLineRunners(SpringApplication.java:675)
	at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:690)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:321)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:139)
	at com.github.pires.hazelcast.Application.main(Application.java:27)
	... 6 more
Caused by: java.lang.NullPointerException
	at com.github.pires.hazelcast.HazelcastDiscoveryController.lambda$run$1(HazelcastDiscoveryController.java:127)
	at com.github.pires.hazelcast.HazelcastDiscoveryController$$Lambda$1/1229004072.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583)
	at com.github.pires.hazelcast.HazelcastDiscoveryController.run(HazelcastDiscoveryController.java:126)
	at org.springframework.boot.SpringApplication.runCommandLineRunners(SpringApplication.java:672)
	... 10 more
```

**Comment by pires** [comment]
@mwielgus did you create the service?

**Comment by mwielgus** [comment]
I probably wasn't clear enough. NPE is throw from Kubernetes E2E test. https://github.com/kubernetes/kubernetes/blob/master/test/e2e/examples.go#L404
Yes, the service is created before.  I run E2E tests on head. 

Apparently it is possible for Kubernetes Endpoints to have subsets without addresses.

**Comment by pires** [comment]
@mwielgus this is probably related to changes with endpoints and subsets. Any hint? This has worked for one or multiple nodes for a long time now.

**Comment by pires** [comment]
@mwielgus does this still apply?
